### ISSUE TITLE
Unexpected token R

### ISSUE THREAD

**Issue by vitalyster** [harshavardhana/minio-lambda#1]
Got this from `thumbnailer-webhook.js` when trying to start minio server with webhook enabled:
```
SyntaxError: Unexpected token R
    at parse (/path/to/thumbnailer/node_modules/body-parser/lib/types/json.js:83:15)
    at /path/to/thumbnailer/node_modules/body-parser/lib/read.js:116:18
    at invokeCallback (/path/to/thumbnailer/node_modules/raw-body/index.js:262:16)
    at done (/path/to/thumbnailer/node_modules/raw-body/index.js:251:7)
    at IncomingMessage.onEnd (/path/to/thumbnailer/node_modules/raw-body/index.js:307:7)
    at emitNone (events.js:105:13)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by harshavardhana** [comment]
The server was fixed to properly send JSON requests closing this. 

```
$ node thumbnail-webhook.js 
Webhook listening on all interfaces at port 3000!
Please update minio server config `~/.minio/config.json` to enable webhook notification target.
{
	"webhook": {
		"1": {
			"enable": true,
			"endpoint": "http://localhost:3000"
		}
	}
}
Once you have edited `~/.minio/config.json` please restart your minio server.

Now we proceed to use "mc" to enable receiving events over webhook.

   $ mc mb myminio/images
   $ mc mb myminio/images-processed
   $ mc events add myminio/images arn:minio:sqs:us-east-1:1:webhook --events put --suffix .jpg
```
